language: rust

matrix:
  include:
    - rust: 1.31.0
    - rust: stable
    - rust: beta
    - rust: nightly
    - env: CARGO_FEATURES=--features i128
      rust: stable
    - env: CROSS_TARGET=mips64-unknown-linux-gnuabi64
      rust: stable
      services: docker
      sudo: required
  allow_failures:
    - rust: nightly

before_script:
  - if [ ! -z "$CROSS_TARGET" ]; then
      rustup target add $CROSS_TARGET;
      cargo install cross --force;
      export CARGO_CMD="cross";
      export TARGET_PARAM="--target $CROSS_TARGET";
    else
      export CARGO_CMD=cargo;
      export TARGET_PARAM="";
    fi

script:
  - $CARGO_CMD test $TARGET_PARAM

branches:
  only:
    - master
